_wandb:
    value:
        cli_version: 0.22.1
        e:
            0qv0rld6uti69df3vsu6l7z0evejjmrf:
                args:
                    - train
                    - --timesteps
                    - "10000"
                codePath: Code_Pranav/RL Code/v6_sc1.py
                codePathLocal: v6_sc1.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "481576673280"
                        used: "163344732160"
                email: pranavlakshman79@gmail.com
                executable: /home/pralak/miniconda3/envs/space_touch/bin/python
                git:
                    commit: adffafd6db5a9439780c98d82f15ddfc0e348b29
                    remote: https://github.com/pranavlakshmanan/Space_Touch.git
                gpu: NVIDIA GeForce RTX 5050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 2560
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5050 Laptop GPU
                      uuid: GPU-68c62f0b-bd09-3cbf-f786-d7b42ccdde20
                host: pop-os
                memory:
                    total: "15920713728"
                os: Linux-6.16.3-76061603-generic-x86_64-with-glibc2.35
                program: /home/pralak/Space_Touch/Code_Pranav/RL Code/v6_sc1.py
                python: CPython 3.9.23
                root: /home/pralak/Space_Touch/Code_Pranav/RL Code
                startedAt: "2025-12-01T07:47:49.273374Z"
                writerId: 0qv0rld6uti69df3vsu6l7z0evejjmrf
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.9.23
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
action_dim:
    value: 10
algorithm:
    value: PPO
curriculum_phases:
    value: 3
hull_points_hand:
    value: 9
hull_points_object:
    value: 32
observation_dim:
    value: 28
overlap_method:
    value: half_space_intersection
position_control:
    value: true
total_timesteps:
    value: 10000
